### ISSUE TITLE
Detect system matio version < 1.5, issue warning

### ISSUE THREAD

**Issue by maedoc** [openmeeg/OpenMEEG-project#2]
[(mailing list thread here)](http://lists.gforge.inria.fr/pipermail/openmeeg-info/2014/000226.html)

When cmake picks up an old version of matio (<1.5, such as the one currently packaged and distributed by the neurodebian repositories v1.3.4), the build fails with 

```
Linking CXX executable OpenMEEGMathsTest-full
../src/libOpenMEEGMaths.so.1.1.0: undefined reference to `Mat_CreateVer'
```

because the old version of matio doesn't provide these functions.

It should be possible to check that the system matio is too old and issuing a warning.

**Comment by papadop** [comment]
This is a good idea. The warning is now in place...

**Comment by papadop** [comment]
I mean in the git repo. It will appear in the next release.
